### ISSUE TITLE
Hornet and Wasp Support

### ISSUE THREAD

**Issue by ncthbrt** [aprescott/bees.rb#1]
Hi there. Are there any plans to support other stinging insects. I have not been able to see so well recently because there are wasps in my eyes. It would be nice to let customers know that.

**Comment by abgoldstein** [comment]
+1 wasps currently in my eyes

**Comment by aprescott** [comment]
To maintain API clarity, bees.rb will likely remain focused strictly on bees for the foreseeable future. 🍯🐝
